apiVersion: v1
kind: Pod
metadata:
  name: s3accesstest
spec:
  serviceAccountName: s3-access-sa
  containers:
  - name: myfirstcontainer
    image: amazon/aws-cli
    command: ["sleep", "3600"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mys3
  # annotations:
  #   kubernetes.io/change-cause: "Updating replica count to 6"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mys3
  template:
    metadata:
      labels:
        app: mys3
    spec:
      serviceAccountName: s3-access-sa
      containers:
      - name: aws-cli
        image: amazon/aws-cli
        command: ["sleep", "3600"]